language: python
python:
  - "2.7"
  - "3.3"
virtualenv:
  system_site_packages: true
before_install:
  - "sudo apt-get install -qq pep8 python-apt python3-apt"
  - "pip install flake8 nose"
# command to run tests
script: make
