language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - "sudo apt-get install -qq pep8 python-apt python3-apt python-requests"
  - "pip install flake8 nose requests"
# command to run tests
script: make
